In [44]:
import numpy as np

In [45]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Slicing of an Array

In [46]:
# This is the basic slicing of one element
arr[5]

6

In [47]:
arr[5:8]

array([6, 7, 8])

In [48]:
arr_slice = arr[5:8]
arr_slice

array([6, 7, 8])

- Numpy doesn't creates a copy of an array for slicing. It performs it on the entire existing array.

In [49]:
# Changing the accessed elements
arr_slice[1] = '123'

In [50]:
arr_slice

array([  6, 123,   8])

In [51]:
arr

array([  1,   2,   3,   4,   5,   6, 123,   8,   9,  10])

- Original array changed.

In [52]:
arr_slice

array([  6, 123,   8])

#### Doing Bare Slice

In [53]:
arr_slice[:] = 64

- Bare Slicing will change all the accessed values.

In [41]:
arr

array([  1, 123,   3,   4,   5,  64,  64,  64,   9,  10])

### Doing slicing on 2d Arrays

In [68]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
# Checking Dimensions
arr2d.ndim

2

In [61]:
arr2d[2]

array([7, 8, 9])

In [62]:
# Accessing the first element
arr2d[0][0]

1

In [64]:
# Accessing the last element
arr2d[2][2]

9

### Doing slicing on 3d Arrays

In [66]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
# Checking Dimensions
arr3d.ndim

3

In [73]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])