In [1]:
import numpy as np

In [31]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Slicing of an Array

In [32]:
# This is the basic slicing of one element
arr[5]

6

In [33]:
arr[5:8]

array([6, 7, 8])

In [34]:
arr_slice = arr[5:8]
arr_slice

array([6, 7, 8])

- Numpy doesn't creates a copy of an array for slicing. It performs it on the entire existing array.

In [36]:
# Changing the accessed elements
arr_slice[1] = '123'

In [37]:
arr_slice

array([  6, 123,   8])

In [38]:
arr

array([  1, 123,   3,   4,   5,   6, 123,   8,   9,  10])

- Original array changed.

In [39]:
arr_slice

array([  6, 123,   8])

#### Doing Bare Slice

In [40]:
arr_slice[:] = 64

In [41]:
arr

array([  1, 123,   3,   4,   5,  64,  64,  64,   9,  10])